Common & Basic Pandas Uses

In [78]:
# 1.Importing Pandas
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic (2).csv

In [79]:
# 2.Load Data
df =pd.read_csv(r'titanic.csv') # Load CSV
# df = read_excel('data/data.xlsx') Load Excel

In [80]:
# 3.View Data
df.head() # First 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Nancy Harper,female,45,3,3,Jmw8908,41.68,J1,S
1,2,1,1,Jamie Hudson,male,74,0,2,LMa1065,286.54,h2,Q
2,3,1,2,Susan Mccullough,female,77,1,3,kyJ6644,241.42,h3,Q
3,4,1,2,Jacob Ryan,male,37,3,1,PTd4784,260.34,S8,Q
4,5,1,3,William Cohen,male,14,3,1,BMY5317,223.01,S7,C

In [81]:
df.tail() # Last 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
195,196,1,1,Susan Abbott,male,33,3,0,WZE5888,353.70,d2,C
196,197,0,3,Courtney Ramirez,male,22,0,2,QDn9398,274.81,X7,Q
197,198,1,3,Brian Garcia,male,27,4,2,GCI3657,65.11,t9,C
198,199,0,1,Renee Russo,male,72,3,4,VZq8933,55.71,V6,Q
199,200,1,2,Jonathan Davidson,male,59,3,2,EjH6847,476.87,V7,S

In [82]:
df.sample(2) # Random 2 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
126,127,1,1,Taylor Smith,male,56,3,0,Ebl6969,53.54,I4,C
22,23,1,1,William Jackson,female,52,0,3,zNw1062,139.43,i6,S

In [83]:
# 4.Inspect Structure
df.shape # Rows and columns

(200, 12)

In [84]:
df.columns # Column names

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [85]:
df.info() # Data types and nulls

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  200 non-null    int64
 1   Survived     200 non-null    int64
 2   Pclass       200 non-null    int64
 3   Name         200 non-null    object
 4   Sex          200 non-null    object
 5   Age          200 non-null    int64
 6   SibSp        200 non-null    int64
 7   Parch        200 non-null    int64
 8   Ticket       200 non-null    object
 9   Fare         200 non-null    float64
 10  Cabin        200 non-null    object
 11  Embarked     200 non-null    object
dtypes: float64(1), int64(6), object(5)
memory usage: 18.9+ KB

In [86]:
df.describe() # Summary stats

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.00000
mean,100.500000,0.525000,2.020000,43.275000,2.010000,1.885000,251.90100
std,57.879185,0.500628,0.801757,22.014371,1.403477,1.449926,134.98115
min,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,21.46000
25%,50.750000,0.000000,1.000000,25.750000,1.000000,1.000000,141.78500
50%,100.500000,1.000000,2.000000,45.000000,2.000000,2.000000,245.47500
75%,150.250000,1.000000,3.000000,62.250000,3.000000,3.000000,356.17250
max,200.000000,1.000000,3.000000,79.000000,4.000000,4.000000,497.06000

In [87]:
# 5.Handling Missing Data
df.isnull().sum() # Count nulls

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [88]:
df.dropna(inplace=True) # Drop rows with any nulls

In [89]:
df['Age'].fillna(df['Age'].mean(),inplace=True) # Fill with mean

/tmp/ipykernel_2206/2731529837.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True) # Fill with mean

In [90]:
# 6.Removing Duplicates
df.duplicated().sum()
df.dropna(inplace=True)

In [91]:
# 7.Selecting Columns
df['Age'] # Single column (Series)

0      45
1      74
2      77
3      37
4      14
       ..
195    33
196    22
197    27
198    72
199    59
Name: Age, Length: 200, dtype: int64

In [92]:
df[['Name','Age']] # Multiple columns (DataFrame)

                  Name  Age
0         Nancy Harper   45
1         Jamie Hudson   74
2     Susan Mccullough   77
3           Jacob Ryan   37
4        William Cohen   14
..                 ...  ...
195       Susan Abbott   33
196   Courtney Ramirez   22
197       Brian Garcia   27
198        Renee Russo   72
199  Jonathan Davidson   59

[200 rows x 2 columns]

In [93]:
# 8.Filtering Rows
df[df['Age'] > 30] # Age > 30

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Nancy Harper,female,45,3,3,Jmw8908,41.68,J1,S
1,2,1,1,Jamie Hudson,male,74,0,2,LMa1065,286.54,h2,Q
2,3,1,2,Susan Mccullough,female,77,1,3,kyJ6644,241.42,h3,Q
3,4,1,2,Jacob Ryan,male,37,3,1,PTd4784,260.34,S8,Q
7,8,1,3,Glenda Reese,female,65,4,1,bpJ0059,80.10,s2,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
193,194,0,1,Christopher Lindsey,female,48,3,3,LgS0190,91.17,V6,S
194,195,1,2,Cynthia Hendricks,female,70,2,4,eKF6306,470.64,L5,S
195,196,1,1,Susan Abbott,male,33,3,0,WZE5888,353.70,d2,C
198,199,0,1,Renee Russo,male,72,3,4,VZq8933,55.71,V6,Q
199,200,1,2,Jonathan Davidson,male,59,3,2,EjH6847,476.87,V7,S

In [94]:
df[df['Sex'] == 'female'] # All females

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Nancy Harper,female,45,3,3,Jmw8908,41.68,J1,S
2,3,1,2,Susan Mccullough,female,77,1,3,kyJ6644,241.42,h3,Q
5,6,0,2,Madison Edwards,female,21,0,4,nOk2542,130.55,l4,Q
7,8,1,3,Glenda Reese,female,65,4,1,bpJ0059,80.10,s2,Q
8,9,0,2,David White,female,6,2,0,Vch5115,480.46,Q2,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
185,186,0,3,Jared Pugh,female,64,3,0,csm8080,116.73,y7,Q
187,188,1,1,Courtney Estrada,female,74,4,3,NfA4470,495.39,U1,C
191,192,0,3,Kelly Ewing,female,72,4,0,OcU7132,163.38,z4,Q
193,194,0,1,Christopher Lindsey,female,48,3,3,LgS0190,91.17,V6,S
194,195,1,2,Cynthia Hendricks,female,70,2,4,eKF6306,470.64,L5,S

In [95]:
df[(df['Age'] > 30) & (df['Sex'] == 'male')] # Compound filter

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,Jamie Hudson,male,74,0,2,LMa1065,286.54,h2,Q
3,4,1,2,Jacob Ryan,male,37,3,1,PTd4784,260.34,S8,Q
9,10,1,2,Tonya Rogers,male,47,1,3,Lky9580,490.35,m3,S
10,11,1,3,Christine Lawrence,male,74,2,0,tcQ6042,186.13,f2,S
14,15,1,3,Ryan Clayton,male,76,4,0,rCq3545,24.98,M5,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
189,190,1,2,Herbert Hartman,male,50,3,2,Sca0806,202.21,W8,Q
190,191,0,3,Steven Fletcher,male,43,0,2,PAw0100,385.06,T0,Q
195,196,1,1,Susan Abbott,male,33,3,0,WZE5888,353.70,d2,C
198,199,0,1,Renee Russo,male,72,3,4,VZq8933,55.71,V6,Q
199,200,1,2,Jonathan Davidson,male,59,3,2,EjH6847,476.87,V7,S

In [96]:
# 9.Sorting Data
df.sort_values(by='Age', ascending=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
101,102,1,1,Sara Mcgrath,female,1,0,0,YUV3231,387.50,C7,S
59,60,1,2,Matthew Palmer,female,2,1,0,gQP0584,361.51,w0,C
135,136,1,3,Dr. Steven Arroyo,female,3,2,3,See3493,107.01,P9,Q
184,185,1,2,Harold Payne,female,3,3,2,Uty5332,147.13,M6,C
175,176,1,1,Mary Richards,male,3,2,4,Ota0669,120.41,l7,C
...,...,...,...,...,...,...,...,...,...,...,...,...
104,105,0,3,Erica Richardson,female,77,1,2,xoQ5824,345.64,f4,Q
141,142,0,1,Brian White,female,77,3,3,MmX6585,497.06,b2,S
114,115,0,2,Curtis Miller,male,78,1,2,TaE6542,284.15,u0,C
183,184,0,3,Tina Ford,female,79,0,2,hAK3730,348.93,W7,S
152,153,1,2,Thomas Kennedy,male,79,4,1,tuD5009,325.56,F9,C

In [97]:
df.sort_values(by=['Pclass', 'Fare'], ascending=[True, False])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
141,142,0,1,Brian White,female,77,3,3,MmX6585,497.06,b2,S
187,188,1,1,Courtney Estrada,female,74,4,3,NfA4470,495.39,U1,C
37,38,0,1,Donald Hamilton,male,9,2,4,Hlr8907,485.22,F3,C
96,97,0,1,Shawn Saunders,male,66,3,2,okE5534,472.01,C0,Q
88,89,0,1,Caroline Harris,female,35,4,4,lpH5948,468.83,h0,C
...,...,...,...,...,...,...,...,...,...,...,...,...
131,132,0,3,Benjamin Porter,female,3,0,4,Mdt5891,56.48,j8,C
0,1,0,3,Nancy Harper,female,45,3,3,Jmw8908,41.68,J1,S
156,157,1,3,Rickey White,female,8,4,0,Jxq7059,40.54,J8,C
14,15,1,3,Ryan Clayton,male,76,4,0,rCq3545,24.98,M5,Q
186,187,1,3,Wendy Roach,male,51,2,1,UvE6139,22.30,q4,C

In [98]:
# 10.Creating New Columns
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

In [99]:
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
145,146,0,2,Rachel Wiggins,female,64,3,2,XKT5616,277.14,s1,S,6
77,78,0,2,Charles Ritter,male,11,2,0,ozS9824,349.21,Z2,Q,3

In [100]:
# 11.Dropping Columns or Rows
df.drop('Ticket', axis=1, inplace=True) # Drop column
df.drop([0, 1], axis=0, inplace=True) # Drop rows by index

In [101]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,FamilySize
2,3,1,2,Susan Mccullough,female,77,1,3,241.42,h3,Q,5
3,4,1,2,Jacob Ryan,male,37,3,1,260.34,S8,Q,5
4,5,1,3,William Cohen,male,14,3,1,223.01,S7,C,5
5,6,0,2,Madison Edwards,female,21,0,4,130.55,l4,Q,5
6,7,0,3,Lindsey Young,male,4,2,1,399.84,d7,Q,4

In [102]:
# 12.Renaming Columns
df.rename(columns={'SibSp': 'SiblingsSpouses'}, inplace=True)

In [103]:
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingsSpouses,Parch,Fare,Cabin,Embarked,FamilySize
79,80,0,1,Alisha Wilkerson,female,59,4,2,345.94,o4,S,7
29,30,1,3,Joseph Whitney,male,25,1,0,464.52,L7,C,2

In [104]:
# 13.Value Counts & Unique
df['Sex'].value_counts()

Sex
male      101
female     97
Name: count, dtype: int64

In [105]:
df['Embarked'].unique()

array(['Q', 'C', 'S'], dtype=object)

In [106]:
df['Embarked'].nunique()

3

In [107]:
# 14.Grouping and Aggregation
df.groupby('Pclass')['Fare'].mean()

Pclass
1    260.055574
2    255.115833
3    243.388462
Name: Fare, dtype: float64

In [108]:
df.groupby('Sex')['Survived'].sum()

Sex
female    52
male      52
Name: Survived, dtype: int64

In [109]:
df.groupby(['Pclass', 'Sex'])['Age'].median()

Pclass  Sex
1       female    47.0
        male      51.0
2       female    43.5
        male      47.0
3       female    47.0
        male      39.0
Name: Age, dtype: float64

In [110]:
# 15. Aggregating Multiple Columns
df.groupby('Pclass').agg({
'Age': ['mean', 'min'],
'Fare': ['max', 'mean']
})

              Age        Fare
             mean min     max        mean
Pclass
1       45.459016   1  497.06  260.055574
2       42.722222   2  492.75  255.115833
3       41.338462   3  490.95  243.388462

In [111]:
# 16. Apply Custom Functions
df['AgeSquared'] = df['Age'].apply(lambda x: x**2)

In [112]:
df.sample(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingsSpouses,Parch,Fare,Cabin,Embarked,FamilySize,AgeSquared
64,65,0,3,Tim Lane,female,47,3,1,336.62,e7,C,5,2209

In [113]:
# 17. String Operations
df['Name'].str.lower()

2       susan mccullough
3             jacob ryan
4          william cohen
5        madison edwards
6          lindsey young
             ...
195         susan abbott
196     courtney ramirez
197         brian garcia
198          renee russo
199    jonathan davidson
Name: Name, Length: 198, dtype: object

In [114]:
df['Name'].str.contains('Mrs')

2      False
3      False
4      False
5      False
6      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: Name, Length: 198, dtype: bool

In [115]:
# 18. Mapping & Replacing Values
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

In [116]:
df['Embarked'].replace({'S': 'Southampton', 'C': 'Cherbourg'}, inplace=True)

/tmp/ipykernel_2206/952687161.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].replace({'S': 'Southampton', 'C': 'Cherbourg'}, inplace=True)

In [117]:
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingsSpouses,Parch,Fare,Cabin,Embarked,FamilySize,AgeSquared
119,120,1,3,Christopher Bruce,0,41,0,0,223.87,h4,Southampton,1,1681
153,154,0,1,Nathan Rios,1,45,3,2,450.72,I3,Q,6,2025

In [118]:
# 19. Combining Columns (concatenation)
df['FullName'] = df['Name'] + ' (' + df['Sex'].astype(str) + ')'

In [119]:
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingsSpouses,Parch,Fare,Cabin,Embarked,FamilySize,AgeSquared,FullName
149,150,1,2,Ashley Ramirez,1,28,3,2,449.81,M5,Q,6,784,Ashley Ramirez (1)
170,171,0,3,Tracey Hall,0,47,2,3,316.62,p8,Cherbourg,6,2209,Tracey Hall (0)

In [120]:
# 20. Merging DataFrames
import numpy as np
df12 = pd.DataFrame({
    "PassengerId": np.arange(1, 201),
    "City": np.random.choice(["Delhi", "Mumbai", "Chennai", "Kolkata"], 200),
    "Salary": np.random.randint(30000, 100000, 200)
})

df12.to_csv("additional.csv", index=False)
df2 = pd.read_csv('additional.csv')
df = pd.merge(df, df2, on='PassengerId', how='left')

In [121]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingsSpouses,Parch,Fare,Cabin,Embarked,FamilySize,AgeSquared,FullName,City,Salary
0,3,1,2,Susan Mccullough,1,77,1,3,241.42,h3,Q,5,5929,Susan Mccullough (1),Chennai,55171
1,4,1,2,Jacob Ryan,0,37,3,1,260.34,S8,Q,5,1369,Jacob Ryan (0),Kolkata,82655
2,5,1,3,William Cohen,0,14,3,1,223.01,S7,Cherbourg,5,196,William Cohen (0),Delhi,34190
3,6,0,2,Madison Edwards,1,21,0,4,130.55,l4,Q,5,441,Madison Edwards (1),Kolkata,71735
4,7,0,3,Lindsey Young,0,4,2,1,399.84,d7,Q,4,16,Lindsey Young (0),Mumbai,49147

In [122]:
# 21. Concatenating DataFrames
df_combined = pd.concat([df, df2], axis=0) # Stack vertically
print(df_combined)

     PassengerId  Survived  Pclass              Name  Sex   Age  \
0              3       1.0     2.0  Susan Mccullough  1.0  77.0
1              4       1.0     2.0        Jacob Ryan  0.0  37.0
2              5       1.0     3.0     William Cohen  0.0  14.0
3              6       0.0     2.0   Madison Edwards  1.0  21.0
4              7       0.0     3.0     Lindsey Young  0.0   4.0
..           ...       ...     ...               ...  ...   ...
195          196       NaN     NaN               NaN  NaN   NaN
196          197       NaN     NaN               NaN  NaN   NaN
197          198       NaN     NaN               NaN  NaN   NaN
198          199       NaN     NaN               NaN  NaN   NaN
199          200       NaN     NaN               NaN  NaN   NaN

     SiblingsSpouses  Parch    Fare Cabin   Embarked  FamilySize  AgeSquared  \
0                1.0    3.0  241.42    h3          Q         5.0      5929.0
1                3.0    1.0  260.34    S8          Q         5.0      1369.0
2                3.0    1.0  223.01    S7  Cherbourg         5.0       196.0
3                0.0    4.0  130.55    l4          Q         5.0       441.0
4                2.0    1.0  399.84    d7          Q         4.0        16.0
..               ...    ...     ...   ...        ...         ...         ...
195              NaN    NaN     NaN   NaN        NaN         NaN         NaN
196              NaN    NaN     NaN   NaN        NaN         NaN         NaN
197              NaN    NaN     NaN   NaN        NaN         NaN         NaN
198              NaN    NaN     NaN   NaN        NaN         NaN         NaN
199              NaN    NaN     NaN   NaN        NaN         NaN         NaN

                 FullName     City  Salary
0    Susan Mccullough (1)  Chennai   55171
1          Jacob Ryan (0)  Kolkata   82655
2       William Cohen (0)    Delhi   34190
3     Madison Edwards (1)  Kolkata   71735
4       Lindsey Young (0)   Mumbai   49147
..                    ...      ...     ...
195                   NaN   Mumbai   64748
196                   NaN  Chennai   78438
197                   NaN    Delhi   64571
198                   NaN  Chennai   99906
199                   NaN   Mumbai   45805

[398 rows x 16 columns]

In [123]:
# 22. Pivot Table
pd.pivot_table(df, values='Fare', index='Pclass', columns='Sex', aggfunc='mean')

Sex              0           1
Pclass
1       252.400909  269.077143
2       257.505294  252.977895
3       258.320294  227.011613

In [124]:
# 23. Resetting and Setting Index
df.reset_index(drop=True, inplace=True)

In [125]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SiblingsSpouses,Parch,Fare,Cabin,Embarked,FamilySize,AgeSquared,FullName,City,Salary
0,3,1,2,Susan Mccullough,1,77,1,3,241.42,h3,Q,5,5929,Susan Mccullough (1),Chennai,55171
1,4,1,2,Jacob Ryan,0,37,3,1,260.34,S8,Q,5,1369,Jacob Ryan (0),Kolkata,82655
2,5,1,3,William Cohen,0,14,3,1,223.01,S7,Cherbourg,5,196,William Cohen (0),Delhi,34190
3,6,0,2,Madison Edwards,1,21,0,4,130.55,l4,Q,5,441,Madison Edwards (1),Kolkata,71735
4,7,0,3,Lindsey Young,0,4,2,1,399.84,d7,Q,4,16,Lindsey Young (0),Mumbai,49147

In [126]:
df.set_index('PassengerId', inplace=True)

In [127]:
df.head()

,Survived,Pclass,Name,Sex,Age,SiblingsSpouses,Parch,Fare,Cabin,Embarked,FamilySize,AgeSquared,FullName,City,Salary
PassengerId,,,,,,,,,,,,,,,
3,1,2,Susan Mccullough,1,77,1,3,241.42,h3,Q,5,5929,Susan Mccullough (1),Chennai,55171
4,1,2,Jacob Ryan,0,37,3,1,260.34,S8,Q,5,1369,Jacob Ryan (0),Kolkata,82655
5,1,3,William Cohen,0,14,3,1,223.01,S7,Cherbourg,5,196,William Cohen (0),Delhi,34190
6,0,2,Madison Edwards,1,21,0,4,130.55,l4,Q,5,441,Madison Edwards (1),Kolkata,71735
7,0,3,Lindsey Young,0,4,2,1,399.84,d7,Q,4,16,Lindsey Young (0),Mumbai,49147

In [128]:
# 24. Conditional Column Creation
df['AgeGroup'] = df['Age'].apply(lambda x: 'child' if x < 16 else 'adult')

In [130]:
df.head()

,Survived,Pclass,Name,Sex,Age,SiblingsSpouses,Parch,Fare,Cabin,Embarked,FamilySize,AgeSquared,FullName,City,Salary,AgeGroup
PassengerId,,,,,,,,,,,,,,,,
3,1,2,Susan Mccullough,1,77,1,3,241.42,h3,Q,5,5929,Susan Mccullough (1),Chennai,55171,adult
4,1,2,Jacob Ryan,0,37,3,1,260.34,S8,Q,5,1369,Jacob Ryan (0),Kolkata,82655,adult
5,1,3,William Cohen,0,14,3,1,223.01,S7,Cherbourg,5,196,William Cohen (0),Delhi,34190,child
6,0,2,Madison Edwards,1,21,0,4,130.55,l4,Q,5,441,Madison Edwards (1),Kolkata,71735,adult
7,0,3,Lindsey Young,0,4,2,1,399.84,d7,Q,4,16,Lindsey Young (0),Mumbai,49147,child

In [132]:
# 25. Save Cleaned Data
df.to_csv('cleaned_titanic.csv', index=False)
df.to_excel('cleaned_data.xlsx', index=False)