Pandas Practice

In [2]:
import numpy as np
import pandas as pd

DATASET 1: Titanic-Like Passenger Dataset
Purpose: Learn data inspection, filtering, missing values, grouping

Create Dataset using NumPy

In [3]:
np.random.seed(1)
rows = 200

df = pd.DataFrame({
    "PassengerId": np.arange(1, rows + 1),
    "Name": np.random.choice(["Mr. John", "Mrs. Anna", "Miss Emma", "Dr. Smith"], rows),
    "Age": np.random.choice(np.append(np.random.randint(1, 80, 180), [np.nan]*20), rows),
    "Sex": np.random.choice(["male", "female"], rows),
    "Pclass": np.random.choice([1, 2, 3], rows),
    "Fare": np.round(np.random.uniform(10, 500, rows), 2)
})

View Data

In [5]:
df.head()

   PassengerId       Name   Age     Sex  Pclass    Fare
0            1  Mrs. Anna  40.0    male       2  461.14
1            2  Dr. Smith   NaN    male       1  333.43
2            3   Mr. John  75.0    male       1  348.14
3            4   Mr. John  63.0  female       2   92.36
4            5  Dr. Smith  39.0  female       1  346.02

In [6]:
df.tail()

     PassengerId       Name   Age     Sex  Pclass    Fare
195          196  Miss Emma  40.0    male       2  136.23
196          197  Dr. Smith  33.0  female       1  300.03
197          198  Mrs. Anna  75.0    male       3   53.22
198          199  Mrs. Anna   NaN    male       2  431.91
199          200  Miss Emma  33.0    male       3   45.51

In [7]:
df.sample(3)

     PassengerId       Name   Age     Sex  Pclass    Fare
56            57  Dr. Smith  23.0  female       1  490.57
23            24   Mr. John  68.0  female       3   33.26
113          114  Dr. Smith  25.0    male       1  208.44

Inspect Structure

In [10]:
df.shape

(200, 6)

In [11]:
df.columns

Index(['PassengerId', 'Name', 'Age', 'Sex', 'Pclass', 'Fare'], dtype='object')

In [12]:
df.info()  # Data types and missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  200 non-null    int64
 1   Name         200 non-null    object
 2   Age          182 non-null    float64
 3   Sex          200 non-null    object
 4   Pclass       200 non-null    int64
 5   Fare         200 non-null    float64
dtypes: float64(2), int64(2), object(2)
memory usage: 9.5+ KB

In [13]:
df.describe() # Statistical summary

       PassengerId         Age      Pclass        Fare
count   200.000000  182.000000  200.000000  200.000000
mean    100.500000   43.318681    2.035000  251.249700
std      57.879185   22.078153    0.804369  146.847353
min       1.000000    1.000000    1.000000   11.250000
25%      50.750000   25.250000    1.000000  115.550000
50%     100.500000   41.000000    2.000000  265.430000
75%     150.250000   63.000000    3.000000  371.432500
max     200.000000   79.000000    3.000000  493.680000

Handle Missing Data

In [14]:
df.isnull().sum()

PassengerId     0
Name            0
Age            18
Sex             0
Pclass          0
Fare            0
dtype: int64

In [18]:
df["Age"].fillna(df["Age"].mean())

0      40.000000
1      43.318681
2      75.000000
3      63.000000
4      39.000000
         ...
195    40.000000
196    33.000000
197    75.000000
198    43.318681
199    33.000000
Name: Age, Length: 200, dtype: float64

Filtering Rows

In [25]:
df[df["Age"]>75]

     PassengerId       Name   Age     Sex  Pclass    Fare
10            11   Mr. John  77.0  female       3  247.52
26            27  Miss Emma  78.0  female       2  441.90
27            28   Mr. John  78.0    male       1  408.35
37            38  Miss Emma  78.0  female       3  377.07
42            43  Mrs. Anna  78.0    male       3  447.31
49            50   Mr. John  77.0  female       3  288.59
85            86  Miss Emma  78.0  female       2  217.45
94            95  Dr. Smith  77.0    male       1  268.22
98            99   Mr. John  78.0    male       2   97.55
114          115  Dr. Smith  77.0  female       2  356.12
126          127  Dr. Smith  78.0  female       3  197.20
130          131  Mrs. Anna  78.0    male       1  459.84
134          135  Miss Emma  77.0    male       2  481.81
139          140  Dr. Smith  77.0    male       3   98.26
140          141  Dr. Smith  79.0  female       2  313.47
144          145   Mr. John  78.0  female       3  431.38
153          154  Mrs. Anna  79.0    male       3  374.59
169          170   Mr. John  79.0    male       1   16.86
176          177  Miss Emma  79.0  female       3   80.42
191          192  Miss Emma  78.0  female       3   12.94

In [26]:
df[df["Sex"]=="female"]

     PassengerId       Name        Age     Sex  Pclass    Fare
3              4   Mr. John  63.000000  female       2   92.36
4              5  Dr. Smith  39.000000  female       1  346.02
5              6  Mrs. Anna  26.000000  female       2  304.88
8              9  Dr. Smith  29.000000  female       3   44.05
10            11   Mr. John  77.000000  female       3  247.52
..           ...        ...        ...     ...     ...     ...
186          187   Mr. John  43.318681  female       1  148.20
190          191  Miss Emma  68.000000  female       1  367.68
191          192  Miss Emma  78.000000  female       3   12.94
193          194  Dr. Smith  43.318681  female       1   25.29
196          197  Dr. Smith  33.000000  female       1  300.03

[99 rows x 6 columns]

Grouping & Aggregation

In [29]:
df.groupby("Pclass")["Fare"].mean()

Pclass
1    237.222623
2    281.545775
3    232.200147
Name: Fare, dtype: float64

DATASET 2: Student Performance Dataset

Purpose: Sorting, value counts, apply, conditional columns

Create Dataset

In [30]:
np.random.seed(2)
rows = 150

df = pd.DataFrame({
    "StudentId": np.arange(1, rows + 1),
    "Age": np.random.randint(18, 30, rows),
    "Gender": np.random.choice(["male", "female"], rows),
    "Course": np.random.choice(["AI", "DS", "ML", "Python"], rows),
    "Marks": np.random.randint(35, 100, rows)
})

In [32]:
df.head()

   StudentId  Age  Gender Course  Marks
0          1   26    male     AI     65
1          2   26  female     DS     41
2          3   24    male     DS     56
3          4   29  female     ML     52
4          5   20  female     AI     72

Sorting Data

In [31]:
df.sort_values(by="Marks",ascending=False)

     StudentId  Age  Gender  Course  Marks
47          48   26  female      DS     99
30          31   26  female      ML     99
140        141   26  female      DS     99
145        146   25  female      ML     99
19          20   22  female  Python     98
..         ...  ...     ...     ...    ...
110        111   29  female      ML     38
40          41   28  female      ML     37
144        145   18  female  Python     37
14          15   22  female      ML     35
11          12   23  female      ML     35

[150 rows x 5 columns]

Value Counts

In [33]:
df["Gender"].value_counts()

Gender
female    84
male      66
Name: count, dtype: int64

Apply Function

In [34]:
df["Result"]=df["Marks"].apply(lambda x:"Pass" if x>=50 else "Fail" )

In [35]:
df.head()

   StudentId  Age  Gender Course  Marks Result
0          1   26    male     AI     65   Pass
1          2   26  female     DS     41   Fail
2          3   24    male     DS     56   Pass
3          4   29  female     ML     52   Pass
4          5   20  female     AI     72   Pass

Grouping

In [36]:
df.groupby("Course")["Marks"].mean()

Course
AI        68.185185
DS        64.611111
ML        62.125000
Python    68.282051
Name: Marks, dtype: float64

DATASET 3: Employee Dataset

Purpose: Rename, drop, mapping, aggregation

Create Dataset

In [57]:
np.random.seed(3)
rows = 120

df = pd.DataFrame({
    "EmpId": np.arange(1, rows + 1),
    "Dept": np.random.choice(["HR", "IT", "Sales"], rows),
    "Salary": np.random.randint(30000, 150000, rows),
    "Gender": np.random.choice(["male", "female"], rows)
})

In [58]:
df.head()

   EmpId   Dept  Salary  Gender
0      1  Sales   36081  female
1      2     HR   56659    male
2      3     IT   53725    male
3      4     HR   54818    male
4      5     HR   58724  female

In [59]:
df.rename(columns={"Dept":"Department"},inplace=True)
df.head()

   EmpId Department  Salary  Gender
0      1      Sales   36081  female
1      2         HR   56659    male
2      3         IT   53725    male
3      4         HR   54818    male
4      5         HR   58724  female

In [60]:
df.drop("Gender",axis=1,inplace=True)
df.head()

   EmpId Department  Salary
0      1      Sales   36081
1      2         HR   56659
2      3         IT   53725
3      4         HR   54818
4      5         HR   58724

Aggregation

In [61]:
df.groupby("Department")["Salary"].agg(["mean","max"])

                    mean     max
Department
HR          85759.094340  149292
IT          92223.166667  145060
Sales       86745.483871  147177